### ISSUE TITLE
Support Stream Deck +

### ISSUE THREAD

**Issue by cbenhagen** [DanTup/streamdeck.dart#1]
Essentially there are three new received events: `dialRotate`, `dialPress` and `touchTap`; and a new sent event, `setFeedback`, which allows the display for the encoder to be updated with a title, value, icon, indicator percentage, etc.

Some more info can be found in the [sample plugins repo](https://github.com/elgatosf/streamdeck-sample-plugins) and  this [reddit comment](https://www.reddit.com/r/StreamDeckSDK/comments/zeug9k/comment/izbb00w/).

**Comment by DanTup** [comment]
Do you know if these are documented in full anywhere? They're not listed at https://developer.elgato.com/documentation/stream-deck/sdk/events-received/ and I can't find any description of the payloads in those repos (at least using GitHub's search 😄).

**Comment by cbenhagen** [comment]
Unfortunately this is all information I have got so far but I will update this issue when I get more.

**Comment by cbenhagen** [comment]
@DanTup the SD+ is now fully documented on https://developer.elgato.com/documentation/stream-deck/sdk/

**Comment by DanTup** [comment]
@cbenhagen thanks! I've started these changes in #2. Are you interested in/able to test them before I publish them in a release? I can provide some instructions on how to compile/install the example plugin from source if you're not sure how to do it (essentially what's in [this shell script](https://github.com/DanTup/streamdeck.dart/blob/25296776ccea5fccd271ea6cec7b311930f6f2cd/example/tool/macos_build_and_install.sh), though it's written for macOS and has hard-coded paths).

**Comment by cbenhagen** [comment]
Awesome! I will give it a try on Monday. Already played with the example a few days ago so it should be pretty straight forward.

**Comment by DanTup** [comment]
Great! I haven't added anything to the example plugin for these yet (because it's hard to know I'm doing things right), but I can have a go if it helps. Otherwise, if you want to try and add a little example for testing, we could commit that as a sample too.

Let me know how it goes! :)

**Comment by DanTup** [comment]
@ChekTek 👋 out of interest, does Elgato have any sort of software emulator/simulator that might help me test this without needing each type of hardware device? I noticed that the normal StreamDeck software can update and show the same as the device, but I can't see a way to use that without the actual hardware device.

**Comment by cbenhagen** [comment]
@DanTup so far everything works as expected. Thanks again!

I added #3 with a simple indicator example. I also played with creating my own elements using the [image plugin](https://pub.dev/packages/image) to create pixmaps. If using external plugins in the examples is ok for you, I can add a PR for that as well.

**Comment by cbenhagen** [comment]
Added a draft for the image example: #6

**Comment by DanTup** [comment]
@cbenhagen awesome, thanks for testing!

Packages in in the example plugin isn't a problem, I'll review that one properly after the other chsanges land/it's rebased and I'm at the machine with my StreamDeck :)

**Comment by ChekTek** [comment]
Unfortunately, Elgato doesn't have an emulator/simulator for Stream Deck yet. 🤞 I'm hopeful we can look into this in the future because I think it would improve the developer experience a lot.

**Comment by DanTup** [comment]
@ChekTek thanks! Where's the best place to keep an eye out for if this happens? (or if it does and you happen to remember this thread and can ping, that would be great too 😄)

**Comment by ChekTek** [comment]
For now, we only have https://www.reddit.com/r/StreamDeckSDK/ as a place for dev news unfortunately... I'm planning on a developer newsletter sometime soon as well. I will do my best to remember to ping here when these things happen. 😅

**Comment by DanTup** [comment]
sgtm! I'll keep me eye out and may ping you sometime in future if I haven't heard anything and wonder if there's been any progress. Thanks!
